package it.petroledge.spotthatcar.repository.schema;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CAR".
 */
public class Car {

    private Long id;
    private java.util.Date feed_date;

    public Car() {
    }

    public Car(Long id) {
        this.id = id;
    }

    public Car(Long id, java.util.Date feed_date) {
        this.id = id;
        this.feed_date = feed_date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getFeed_date() {
        return feed_date;
    }

    public void setFeed_date(java.util.Date feed_date) {
        this.feed_date = feed_date;
    }

}
